---
title: "Final"
subtitle: "Eli Dewald"
date: "May 27, 2025"
format: html
toc: true
---
[GitHub Repository](https://github.com/eliasdewald/ENVS-193DS_spring-2025_final)
```{r}
#| message: false # make messages not show
#| warning: false # make warnings not show

library(tidyverse) # general use
library(here) # file organization
library(MuMIn) # choosing best model
library(janitor) # cleaning data frames
library(DHARMa) # running model diagnostics

sst <- read.csv( # read in data
  here("data", "SST_update2023.csv")) # set file path
```

# Problem 1. Research Writing 

## a. 

In part 1, they conducted a Pearson's correlation coefficient test to study the correlation between the two variables. In part 2, they conducted an ANOVA test to study whether there were significant differences in means between more than two sources.

## b. 

A Tukey's multiple comparisons of mean test could be used to find Tukey's HSD, which would be useful for discerning which sources have significant differences between them in average nitrogen load (kg year-1). Running an Effect Size for an ANOVA test could be used to find η~2~, which would be useful to study how much source explains average nitrogen load (kg year-1). 

## c. 

We found that there is a [blank] (r = correlation coefficient) correlation between distance from headwater (km) and annual total nitrogen load (kg year-1) (Pearson' R test, t(degrees of freedom) = t-statistic, p = 0.03, α = significance level). 

We found a [blank] (η~2~ = effect size) difference between sources (urban land, atmospheric deposition, fertilizer, wastewater treatment, and grasslands) in nitrogen load (kg year-1) (one-way ANOVA, f(among groups degrees of freedom, within groups degrees of freedom) = f-statistic, p = 0.02, α = significance level). On average, [blank] sources tended to have [blank] nitrogen load than [blank, etc.] (Tukey HSD, 95% CI:[lower bound, upper bound] (kg year-1)) sources. 
